### ISSUE TITLE
Cannot print when a space is in filename.

### ISSUE THREAD

**Issue by nightlife90** [CGessinger/nextcloud-skyprint#1]
Its not possible to print when a space character is in the filename. 

Printing failed: lp -d HP /var/www/cloud********.at/web/data/user/files/print/test 3.pdf -n 1 -o orientation-requested=3 -o media=a4 -o number-up=1 with output: lp: Error - unable to access "/var/www/cloud********.at/web/data/user/files/print/test" - No such file or directory

the original filename was "test 3.pdf"
when the filename gets renamed to "test3.pdf" it works.

**Comment by CGessinger** [comment]
You are right, I didn't notice that. This should be an easy fix though. I will fix this as soon as I can 👍🏼

**Comment by nightlife90** [comment]
Thanks for the ultimate fast repair ;)
