### ISSUE TITLE
Bad argument for new Process(), NextCloud 27

### ISSUE THREAD

**Issue by cejkato2** [CGessinger/nextcloud-skyprint#2]
Dear @CGessinger,
thank you for this NextCloud app.

I have Nextcloud Hub 6 (27.1.4) and tried to install nextcloud-skyprint.
Unfortunately, there was an error with `new Process()` calls (in `getPrinters()` and `print()`):

```
Symfony\\Component\\Process\\Process::__construct(): Argument #1 ($command) must be of type array, string given, called in /.../apps/skyprint/lib/Service/PrintService.php on line 50
```

I've tried to rewrite it to:
```
$process = Process::fromShellCommandline($command);
...
$process = Process::fromShellCommandline("lpstat -p | awk '{print $2}'");
```
and it works.

I'm not expert in Symfony and its compatibility - if you think `fromShellCommandline()` is a good solution, I can send my simple patch...

**Comment by CGessinger** [comment]
Thank you for opening this issue. I knew this was a problem but I thought Symfony was able to handle it anyway. Unfortunately it seems like it doesnt. 

The method`fromShellCommandline()` can be used here, but the recommended way to define commands is to split them into an array of arguments. So I will try this first.

I am on it and will fix this within the next 24hrs! 👍🏼

**Comment by CGessinger** [comment]
This issue should now be fixed. Please feel free to test it and report back to me if it works now. Thanks!
