### ISSUE TITLE
PlugIn works not in Nextcloud Hub 7 (28.0.1)

### ISSUE THREAD

**Issue by bassemolufda** [CGessinger/nextcloud-skyprint#4]
Hello,

Thank you very much for programming this plugin. In Nextclod version 27.1.5 it worked fine.

In Nextcloud version 28.0.1 it no longer works. There is also no print menu offered to display Skyprint to print a document.

Error in Log-File:

Level: Fatal
Application: no app in context

Call to undefined method OC\Server::getEventDispatcher()
Could not boot skyprint: Call to undefined method OC\Server::getEventDispatcher()

Sincelery Uwe

--------------------------------------------------------------------------------------------------------------------------------------
Error
Call to undefined method OC\Server::getEventDispatcher()
/usr/share/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php
Zeile 200
OCA\SkyPrint\AppInfo\Application->boot()
/usr/share/nextcloud/lib/private/App/AppManager.php
Zeile 434
OC\AppFramework\Bootstrap\Coordinator->bootApp()
/usr/share/nextcloud/lib/private/App/AppManager.php
Zeile 213
OC\App\AppManager->loadApp()
/usr/share/nextcloud/lib/private/legacy/OC_App.php
Zeile 125
OC\App\AppManager->loadApps()
/usr/share/nextcloud/lib/base.php
Zeile 1067
OC_App::loadApps()
/usr/share/nextcloud/index.php
Zeile 39
OC::handleRequest()

**Comment by CGessinger** [comment]
Hello Uwe,
your are right, Skyprint does not support nextcloud 28 yet. I will need to read through the nextcloud docs as it apperas they made breaking changes concerning File actions. I am working on it though!

**Comment by bassemolufda** [comment]
Hello Christian Gessinger,
I will wait patiently for a new version of the plugin. Thank you for your work and time you invest.
Sincelery Uwe

**Comment by CGessinger** [comment]
Its good news! Skyprint is now available for Nextcloud 28 and 29
